### ISSUE TITLE
Esp8266fs tool dont visible in menu after update on Arduino 1.8.2

### ISSUE THREAD

**Issue by pilnikov** [esp8266/arduino-esp8266fs-plugin#31]
Arduino 1.8.2 banned Esp8266fs tool in menu. In 1.8.1 all work.

**Comment by DarkiStar** [comment]
for me it works without problems in 1.8.2

**Comment by pilnikov** [comment]
version your Windows? My is 10x64 prof

**Comment by DarkiStar** [comment]
Same Windows Version on my side.

**Comment by pilnikov** [comment]
Please show your path to the plugin

**Comment by DarkiStar** [comment]
D:\Downloads\arduino-1.8.2\tools\ESP8266FS\tool\esp8266fs.jar

**Comment by DarkiStar** [comment]
Would like to know if it works for you now ...

**Comment by pilnikov** [comment]
No, it does not work. I checked all the paths, updated the version to 0.3.0. Did not help.

**Comment by DarkiStar** [comment]
And you have selected an ESP8266 Board? Just to be sure ...

![esp8266_sketch_data_upload](https://cloud.githubusercontent.com/assets/23613040/24918683/7e49a61c-1ee1-11e7-9408-9e0c605bea01.png)

**Comment by pilnikov** [comment]
![1](https://cloud.githubusercontent.com/assets/25922873/24918816/1bd3c322-1efb-11e7-963f-4f985b171da1.JPG)

**Comment by pilnikov** [comment]
![2](https://cloud.githubusercontent.com/assets/25922873/24918900/6e99e50a-1efb-11e7-94ea-57d1c0e46e95.JPG)

**Comment by pilnikov** [comment]
I repaired everything! Has earned !!!! Was c:\Program Files (x86)\Arduino\tools\ESP8266FS\tool**s**\  ... It is necessary so c:\Program Files (x86)\Arduino\tools\ESP8266FS\too**l**\
Thank you so much!
