### ISSUE TITLE
SPIFFS Not Defined for NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200

### ISSUE THREAD

**Issue by vaemc** [esp8266/arduino-esp8266fs-plugin#52]
![image](https://user-images.githubusercontent.com/16460137/53108410-f0db6f00-3571-11e9-84fb-818e9f06c796.png)

Clicking 'ESP8266 Sketch Data Upload' will display an error

**Comment by GarveyZuo** [comment]
tool -> flash-size -> choose 3M spfss

**Comment by msvadakkan** [comment]
not working showing the same error

**Comment by rohoop** [comment]
same here

**Comment by Lassska** [comment]
tools / Erase Flash / All flash contents     (for first upload)
tools / Flash Size / 4M (1-2-3M SPIFFS)
done
