### ISSUE TITLE
Plugin warns about "empty spiffs" if subdirectory is used

### ISSUE THREAD

**Issue by mhaas** [esp8266/arduino-esp8266fs-plugin#6]
My files are located in data/wwwroot/; all files are in that particular directory and no regular files are located immediately below data/.

In this case, the plugin warns me that I'm about to create an empty spiffs. If I click "yes", the plugin proceeds to upload a correct (including all files) spiffs image.

**Comment by ajcord** [comment]
I have the same issue in one of my projects. I added a dummy.txt in `data/` to silence the warning, but it shouldn't warn in the first place if it works.

**Comment by me-no-dev** [comment]
https://github.com/esp8266/arduino-esp8266fs-plugin/commit/68fd73873203a78018bbcc3dd7b2f04f5976befb
done!
