### ISSUE TITLE
 SPIFFS Upload failed!

### ISSUE THREAD

**Issue by roncoa** [esp8266/arduino-esp8266fs-plugin#64]
After updating the core of esp8266 2.6.1 the tool does not work anymore.
Are there any suggestions?
Thanks

![Immagine 1](https://user-images.githubusercontent.com/19438993/68981425-9b33aa80-0803-11ea-88d8-eb58b3a522ae.jpg)

**Comment by ArcadeNut** [comment]
i have to same issue

**Comment by tihoangyeudau** [comment]
i have same issue

**Comment by i486you** [comment]
i have the same issue

**Comment by TWJubb** [comment]
Same issue for me... Reverted to ESP8266 Community version 2.6.0 (from 2.6.1) and the SPIFFS upload worked fine.

**Comment by tihoangyeudau** [comment]
> Same issue for me... Reverted to ESP8266 Community version 2.6.0 (from 2.6.1) and the SPIFFS upload worked fine.

but we wish it will work with 2.6.1

**Comment by SunnyPage** [comment]
i have same issue

**Comment by DiegoMisa** [comment]
same issue

**Comment by DiegoMisa** [comment]
downgrade to 2.5.2 and work fine

**Comment by i486you** [comment]
I found it out how to upload files by using command line.
(Don't forget to close Serial Monitor window when uploading.
 And my laptop is a macbook. You could find a clue from my solution if you use windows OS.)

1. Pack the folder data that files is located in to upload.
**> ./mkspiffs -c /Users/<username>/Documents/Arduino/Test_SPIFFS/data -b 4096 -p 256 spiffs.bin**
   + Refer to: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/storage/spiffs.html
   + Path of mkspiffs: /Users/<username>/Library/Arduino15/packages/esp8266/tools/mkspiffs/2.5.0-4-b40a506
 
2. Upload the image file packed.
**> esptool.py --chip esp8266 --port /dev/cu.SLAB_USBtoUART --baud 115200 write_flash 0xEB000 spiffs.bin**

     + You might get the error 'A fatal error occurred: Timed out waiting for packet header' after uploading. However, just ignore it if the console says 'Wrote ... ' before the error line, and then check if the file is uploaded by following the next step.
    + 0xEB000 is the start address of SPIFFS. You can find it when you try to upload files by clicking on menu button 'Tools > ESP8266 Sketch Data Upload', and then check '[SPIFFS] address: 0xEB000' on the console like the following captured image. 
<img width="707" alt="Screen Shot 2019-11-22 at 7 29 24 AM" src="https://user-images.githubusercontent.com/1716002/69365758-dd745480-0cf9-11ea-8d2e-2d96f53d22bf.png">

3. Check if the file uploaded successfully.
**> esptool.py --chip esp8266 --port /dev/cu.SLAB_USBtoUART --baud 115200 read_flash 0xEB000 0x1000 backout.txt**
    + 0x1000 is the size of memory to read.
<img width="788" alt="Screen Shot 2019-11-22 at 7 37 13 AM" src="https://user-images.githubusercontent.com/1716002/69366292-efa2c280-0cfa-11ea-9136-349703ddef70.png">

I hope that it is helpful for you.

**Comment by hznupeter** [comment]
i have same issue in esp8266 2.6.1

**Comment by RudyFiero** [comment]
Will this be fixed soon?

**Comment by smartswitchsio** [comment]
i have same issue in esp8266 2.6.1

**Comment by 2color** [comment]
This is probably related to https://github.com/esp8266/Arduino/pull/6765 which was introduced in `2.6.1`

**Comment by me-no-dev** [comment]
plugin has been updated to 0.5.0 :) please give it a try

**Comment by tihoangyeudau** [comment]
> plugin has been updated to 0.5.0 :) please give it a try

it makes my arduino can not startup

**Comment by arthurhoch** [comment]
Arduino 1.8.8, arduino-esp8266fs-plugin 0.40 and esp8266 by ESP8266 Community 2.6.0 works.

**Comment by RudyFiero** [comment]
> it makes my arduino can not startup

I can confirm this. It worked before the plugin update. I have both a a Windows installer version and a Portable install. Both will not run. After I remove 0.5 then it runs.

Arduino 1.8.10 and ESP8266 2.6.1

**Comment by hznupeter** [comment]
i've go back to esp8266 2.5.2,it's more safe

**Comment by me-no-dev** [comment]
the zip has been updated with earlier java. Please try again :)

**Comment by RudyFiero** [comment]
Arduino starts, but still "**SPIFFS upload failed!**"

**Comment by ghost** [comment]
Same issue with 2.5.2.

**Comment by tihoangyeudau** [comment]
> Arduino starts, but still "**SPIFFS upload failed!**"

#68

**Comment by masoud935** [comment]
hi all... I have a same issue...but I found the solution
IDE is 1.8.10  and esp is2.5.2
change your jar file to 
[ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)

**Comment by jpasqua** [comment]
Also failing for me on esp 2.6.1, ide 1.8.10, and plugin v5 (actually I tried every released plugin and they all fail with different messages). I am not in a position to downgrade to 2.5.2. I will try the manual uploading steps mentioned above to see if I can get that to work until this is fixed.

**Comment by RudyFiero** [comment]
To get around the failure I had used the web upload code from the FSbrowser.ino example and put that into the program I wanted to use. I wanted to try out someone else's examples and their program made use of SPIFFS.

**Comment by jpasqua** [comment]
[UPDATE] Upon further investigation the plugin seems fine. I was able to make my system work with a minor change upload.py. I picked up the copy from [here](https://github.com/esp8266/Arduino/blob/master/tools/upload.py) and made a few minor changes that you can see in the diffs below. It adds an extra test to see whether the argument is a file and saves it in the 'binary' variable. I've tested the following cases: (1) Downloading a sketch and erasing the sketch only, (2) Downloading a sketch and erasing the entire SPIFFS area, and (3) Downloading the data directory using the plugin

Hope it's useful, but YMMV.

    49,52c49
    <         if os.path.isfile(thisarg):
    <             binary = thisarg
    <         else:
    <             cmdline = cmdline + [thisarg]
    ---
    >         cmdline = cmdline + [thisarg]


-----
Thanks to @i486you for the guidance on the manual process. I have it working now (though I had to download a separate copy of mkspiffs for some reason). I tried to just debug the plugin, but I couldn't find a java version that was compatible with the IDE. It would fail on launch saying my plugin was compiled with too new a version of Java. I backed off versions a bit, but no joy. Hopefully it will be an easy fix. It seems to just be generating an incorrect command line.

**Comment by coolpixel** [comment]
> hi all... I have a same issue...but I find solve it.
> IDE is 1.8.10 and esp is2.5.2
> change your jar file to
> [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)

it works for me ... thanks

**Comment by PersonalityFox** [comment]
> hi all... I have a same issue...but I found the solution
> IDE is 1.8.10 and esp is2.5.2
> change your jar file to
> [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)

its work with ide 1.8.9
Thank you

**Comment by Bob0505** [comment]
> > hi all... I have a same issue...but I found the solution
> > IDE is 1.8.10 and esp is2.5.2
> > change your jar file to
> > [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)
> 
> its work with ide 1.8.9
> Thank you

may I know which version about ESP8266FS.zip ?

**Comment by PersonalityFox** [comment]
> > > hi all... I have a same issue...but I found the solution
> > > IDE is 1.8.10 and esp is2.5.2
> > > change your jar file to
> > > [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)
> > 
> > 
> > its work with ide 1.8.9
> > Thank you
> 
> may I know which version about ESP8266FS.zip ?

i dont know
may be @masoud935 knows answer to this question

**Comment by anctsys** [comment]
Hi
Just a little precision, for ide arduino 1.8.10 you must download the last ESP8266FS last release on
https://github.com/esp8266/arduino-esp8266fs-plugin/releases/
Bruno

**Comment by masoud935** [comment]
> > hi all... I have a same issue...but I find solve it.
> > IDE is 1.8.10 and esp is2.5.2
> > change your jar file to
> > [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)
> 
> it works for me ... thanks

😁😁😁

**Comment by masoud935** [comment]
> > > hi all... I have a same issue...but I found the solution
> > > IDE is 1.8.10 and esp is2.5.2
> > > change your jar file to
> > > [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)
> > 
> > 
> > its work with ide 1.8.9
> > Thank you
> 
> may I know which version about ESP8266FS.zip ?



> > > hi all... I have a same issue...but I found the solution
> > > IDE is 1.8.10 and esp is2.5.2
> > > change your jar file to
> > > [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)
> > 
> > 
> > its work with ide 1.8.9
> > Thank you
> 
> may I know which version about ESP8266FS.zip ?

I don't know which version this is.
I just know this version is working properly

**Comment by anctsys** [comment]
@masoud935 
> I don't know which version this is.
> I just know this version is working properly

My configuration
IDE is 1.8.10
ESP8266 WEMOS D1 mini 
Flash size: 4MB
esptool.py v2.8

This is my process to upload data into FS for ESP32 and ESP8266
- Add the last library of esp8266fs into tools directory  (https://github.com/esp8266/arduino-esp8266fs-plugin/releases/)
- Select Erase Flash to Only Sketch to tools for your board configuration. Because erase your data FS after each upload of your sketch
- Upload your data directroy with the tools ESP8266 or 32

**Comment by roncoa** [comment]
Solved with
https://github.com/esp8266/arduino-esp8266fs-plugin/releases/download/0.5.0/ESP8266FS-0.5.0.zip

**Comment by Bob0505** [comment]
> hi all... I have a same issue...but I found the solution
> IDE is 1.8.10 and esp is2.5.2
> change your jar file to
> [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)

Dear @masoud935 ,

May I know which version of attach file(ESP8266FS.zip)?
It's work with Arduino IDE Ver.1.8.10

Thank you very much!

**Comment by rezaajdarkosh** [comment]
> Hi
> Just a little precision, for ide arduino 1.8.10 you must download the last ESP8266FS last release on
> https://github.com/esp8266/arduino-esp8266fs-plugin/releases/
> Bruno

**Comment by rezaajdarkosh** [comment]
Thank you very much!

**Comment by antonadamec** [comment]
No needed to downgrade, just updated from 
https://github.com/esp8266/arduino-esp8266fs-plugin/releases/

I am using IDE 1.8.12

**Comment by Aaqu** [comment]
> No needed to downgrade, just updated from
> https://github.com/esp8266/arduino-esp8266fs-plugin/releases/
> 
> I am using IDE 1.8.12

I using IDE 1.8.12

`sptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'write_flash'`

help

**Comment by Aaqu** [comment]
> > No needed to downgrade, just updated from
> > https://github.com/esp8266/arduino-esp8266fs-plugin/releases/
> > I am using IDE 1.8.12
> 
> I using IDE 1.8.12
> 
> `sptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'write_flash'`
> 
> help

Thank you, I need update esp libray to 2.6.3

**Comment by alireza-azar** [comment]
> 
> 
> hi all... I have a same issue...but I found the solution
> IDE is 1.8.10 and esp is2.5.2
> change your jar file to
> [ESP8266FS.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/3908067/ESP8266FS.zip)

thank you so much bro this is work for me

**Comment by omarnas** [comment]
I have the same issue and my solution was going back to an older version of upload.py (attached below )
[upload.py.zip](https://github.com/esp8266/arduino-esp8266fs-plugin/files/5178418/upload.py.zip) replace it with the existing one (/Users/YOUUSER/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/upload.py)

**Comment by denimjeans** [comment]
Version 0.5.0 does not work for me with 18.10 and on Windows 10. 
Filesystem will be created ok, but uploading does not work. 
Workaround as suggested by @i486you helped me. Here is what needed to do:

change to folder:
`C:\Users\YOUR_USER_NAME\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\tools\esptool>`
`
esptool.py --chip esp8266 --port com4 --baud 115200 write_flash 0x200000  C:\Users\YOUR_USER_NAME\AppData\Local\Temp\arduino_build_225904\WIFI_IR_BLASTER.spiffs.bin
`
address might be different for your usecase.  You will find all attributes if you scroll little up. 

Hope they will fix it soon, it's kind of messy, but works for me.

**Comment by denimjeans** [comment]
Solved: 
I needed to update my ESP development enviroment: 
**Tools-> Board->Boardmanager**, Update ESP8266 to 3.0.2, then try again. It works for me. I was at 2.6.1 before... 
tested on windows 10, Arduino 18.10 and 18.19, ESP8266 v 3.0.2.
