### ISSUE TITLE
ESP8266FS-0.5.0 makes arduino not startup

### ISSUE THREAD

**Issue by tihoangyeudau** [esp8266/arduino-esp8266fs-plugin#67]
when i update to ESP8266FS-0.5.0, it makes arduino not startup, when i delete it , i can open arduino.

**Comment by staffa007** [comment]
same problem!

**Comment by me-no-dev** [comment]
which version IDE?

**Comment by arthurhoch** [comment]
> which version IDE?

1.8.10

**Comment by staffa007** [comment]
1.8.10 both Mac OS and Windows

**Comment by arthurhoch** [comment]
Arduino 1.8.8, arduino-esp8266fs-plugin 0.40 and esp8266 by ESP8266 Community 2.6.0 works.
For emergency.

**Comment by rousir** [comment]
same problem!windows 7,arduino ide 1.8.9,

**Comment by me-no-dev** [comment]
the zip has been updated with earlier java. Please try again :)

**Comment by tihoangyeudau** [comment]
it works. i can open arduino. but i cant upload fs, there is the issue:

...
[SPIFFS] upload  : C:\Users\tuant\AppData\Local\Temp\arduino_build_426210/demo.spiffs.bin
[SPIFFS] address  : 0x300000
[SPIFFS] reset    : --before default_reset --after hard_reset
[SPIFFS] port     : COM4
[SPIFFS] speed    : 115200
[SPIFFS] python   : C:\Users\tuant\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1\python3.exe
[SPIFFS] uploader : C:\Users\tuant\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\tools\upload.py

usage: esptool write_flash [-h] [--erase-all]

                           [--flash_freq {keep,40m,26m,20m,80m}]

                           [--flash_mode {keep,qio,qout,dio,dout}]

                           [--flash_size FLASH_SIZE]

                           [--spi-connection SPI_CONNECTION] [--no-progress]

                           [--verify] [--encrypt]

                           [--ignore-flash-encryption-efuse-setting]

                           [--compress | --no-compress]

                           <address> <filename> [<address> <filename> ...]

esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'write_flash'

SPIFFS Upload failed!

**Comment by tihoangyeudau** [comment]
> it works. i can open arduino. but i cant upload fs, there is the issue:
> 
> ...
> [SPIFFS] upload : C:\Users\tuant\AppData\Local\Temp\arduino_build_426210/demo.spiffs.bin
> [SPIFFS] address : 0x300000
> [SPIFFS] reset : --before default_reset --after hard_reset
> [SPIFFS] port : COM4
> [SPIFFS] speed : 115200
> [SPIFFS] python : C:\Users\tuant\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1\python3.exe
> [SPIFFS] uploader : C:\Users\tuant\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\tools\upload.py
> 
> usage: esptool write_flash [-h] [--erase-all]
> 
> ```
>                        [--flash_freq {keep,40m,26m,20m,80m}]
> 
>                        [--flash_mode {keep,qio,qout,dio,dout}]
> 
>                        [--flash_size FLASH_SIZE]
> 
>                        [--spi-connection SPI_CONNECTION] [--no-progress]
> 
>                        [--verify] [--encrypt]
> 
>                        [--ignore-flash-encryption-efuse-setting]
> 
>                        [--compress | --no-compress]
> 
>                        <address> <filename> [<address> <filename> ...]
> ```
> 
> esptool write_flash: error: argument
> 
> : [Errno 2] No such file or directory: 'write_flash'
> SPIFFS Upload failed!
